"""create initial database tables

Revision ID: a483654aaeca
Revises: 
Create Date: 2026-10-09 12:33:26.172032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a483654aaeca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=200), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('body_digest', sa.String(length=64), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mqtt_challenges_challenge_id'), 'mqtt_challenges', ['challenge_id'], unique=True)
    op.create_table('production_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_sources_source_id'), 'production_sources', ['source_id'], unique=True)
    op.create_table('submission_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=150), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_attempts_classification'), 'submission_attempts', ['classification'], unique=False)
    op.create_index(op.f('ix_submission_attempts_event_id'), 'submission_attempts', ['event_id'], unique=False)
    op.create_index(op.f('ix_submission_attempts_source_id'), 'submission_attempts', ['source_id'], unique=False)
    op.create_table('production_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('target_event_id', sa.String(length=150), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['production_sources.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'event_id', name='uq_production_event_source_event')
    )
    op.create_index(op.f('ix_production_events_source_id'), 'production_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_production_events_status'), 'production_events', ['status'], unique=False)
    op.create_table('acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_pk', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_pk'], ['production_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acknowledgements_event_pk'), 'acknowledgements', ['event_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acknowledgements_event_pk'), table_name='acknowledgements')
    op.drop_table('acknowledgements')
    op.drop_index(op.f('ix_production_events_status'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_source_id'), table_name='production_events')
    op.drop_table('production_events')
    op.drop_index(op.f('ix_submission_attempts_source_id'), table_name='submission_attempts')
    op.drop_index(op.f('ix_submission_attempts_event_id'), table_name='submission_attempts')
    op.drop_index(op.f('ix_submission_attempts_classification'), table_name='submission_attempts')
    op.drop_table('submission_attempts')
    op.drop_index(op.f('ix_production_sources_source_id'), table_name='production_sources')
    op.drop_table('production_sources')
    op.drop_index(op.f('ix_mqtt_challenges_challenge_id'), table_name='mqtt_challenges')
    op.drop_table('mqtt_challenges')
    # ### end Alembic commands ###
